import yfinance as yf
import pandas as pd
import ta
import feedparser
import urllib.parse

def get_market_news(ticker: str, limit: int = 5) -> list:
    """
    Fetches latest news headlines from Google News RSS by ticker.
    """
    try:
        query = urllib.parse.quote(f"{ticker} stock news")
        rss_url = f"https://news.google.com/rss/search?q={query}&hl=en-US&gl=US&ceid=US:en"
        feed = feedparser.parse(rss_url)
        
        news_items = []
        for entry in feed.entries[:limit]:
            news_items.append({
                "title": entry.title,
                "link": entry.link,
                "published": entry.published
            })
        return news_items
    except Exception as e:
        print(f"News Fetch Error: {e}")
        return []

def get_stock_data(ticker: str, period: str = "2y"):
    """
    Fetches historical stock data from Yahoo Finance.
    """
    ticker = ticker.upper()
    df = yf.download(ticker, period=period, interval="1d", progress=False)
    
    if df.empty:
        raise ValueError(f"No data found for ticker: {ticker}")
        
    # Validating MultiIndex columns (yfinance update)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
        
    return df

def add_technical_indicators(df: pd.DataFrame):
    """
    Adds Technical Indicators (RSI, MACD, SMA, Bollinger Bands) to the DataFrame.
    """
    df = df.copy()
    
    # Fill missing values if any
    df = df.ffill().bfill()

    # RSI (Relative Strength Index)
    df['RSI'] = ta.momentum.RSIIndicator(close=df['Close'], window=14).rsi()

    # MACD (Moving Average Convergence Divergence)
    macd = ta.trend.MACD(close=df['Close'])
    df['MACD'] = macd.macd()
    df['MACD_Signal'] = macd.macd_signal()

    # SMA (Simple Moving Averages)
    df['SMA_50'] = ta.trend.SMAIndicator(close=df['Close'], window=50).sma_indicator()
    df['SMA_200'] = ta.trend.SMAIndicator(close=df['Close'], window=200).sma_indicator()

    # Bollinger Bands
    bb = ta.volatility.BollingerBands(close=df['Close'], window=20)
    df['BB_High'] = bb.bollinger_hband()
    df['BB_Low'] = bb.bollinger_lband()

    # Clean NaN values generated by indicators
    df = df.dropna()
    
    return df

def get_analysis_data(ticker: str):
    """
    Orchestrator to get clean, feature-rich data for a ticker.
    """
    raw_df = get_stock_data(ticker)
    processed_df = add_technical_indicators(raw_df)
    return processed_df
